org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
gradle.user.home=/home/user/.gradle
org.gradle.caching=true
# systemProp.http.proxyHost=172.19.0.1
# systemProp.https.proxyHost=172.19.0.1
# systemProp.https.proxyPort=8080
# systemProp.http.proxyPort=8080